# Generated by Django 5.1.2 on 2024-11-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_estoqueproduto_saldo_alter_estoqueproduto_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueEntrada',
            fields=[
            ],
            options={
                'verbose_name': 'estoque_entrada',
                'verbose_name_plural': 'estoque_entrada',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stock.estoque',),
        ),
        migrations.CreateModel(
            name='EstoqueSaida',
            fields=[
            ],
            options={
                'verbose_name': 'estoque_saida',
                'verbose_name_plural': 'estoque_saida',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stock.estoque',),
        ),
    ]
