# Generated by Django 5.1.2 on 2024-11-12 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_estoqueentrada_estoquesaida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoqueentrada',
            options={'verbose_name': 'Estoque etrada', 'verbose_name_plural': 'Estoque entrada'},
        ),
        migrations.AlterModelOptions(
            name='estoquesaida',
            options={'verbose_name': 'Estoque saida', 'verbose_name_plural': 'Estoque saida'},
        ),
    ]
