# Generated by Django 5.1.2 on 2024-11-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_estoqueentrada_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoqueentrada',
            options={'verbose_name': 'Estoque entrada', 'verbose_name_plural': 'Estoque entrada'},
        ),
    ]
