# Generated by Django 5.1.2 on 2024-11-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_estoque_movimento_alter_estoque_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricoEstoque',
        ),
    ]
